export const CONFIG = {
  title: "Dino Type Racer",
  storageKey: "typing-race:v1",
  calibrationSeconds: 60,
  quickRaceParagraphs: [
    "A little raptor kicks dust from the starting line while the jungle drums count down. Keep your eyes on the next letter, stay loose, and race the dinosaurs to the finish.",
    "The canyon wind carries a silly cheer from the crowd. The racers lean forward, the tape trembles, and one tiny comet of a dinosaur starts the whole parade.",
    "At sunrise the track glows gold, then green, then bright again. The runners wobble, recover, and keep chasing the cleanest line they can find.",
    "A triceratops referee blows the whistle and the whole field laughs. After that, the typing gets serious very fast, because the finish line never waits.",
    "Two velociraptors wager snacks on the race and immediately regret it. The typing begins, the pace sharpens, and the snacks become a very distant problem.",
    "The stadium lights flicker on one by one like friendly eyes. Every runner gets a turn to feel fast, but only the quietest hands usually win.",
    "A curious hatchling counts the lanes out loud and forgets to count the dinosaurs. That is fine, because the starting horn solves the mystery.",
    "The track bends past a fern forest, a lava rock arch, and a puddle that reflects the whole sky. The racers keep moving because the sentence is almost done.",
    "One dinosaur wears a paper crown, mostly for luck and partly for style. Another dinosaur pretends not to care, then sprints a little harder anyway.",
    "When the dust settles, the scoreboard says the winner was calm first and fast second. That turns out to be useful advice for typing too.",
    "A pair of friendly bots practice laps while the player lines up at the rail. The bots do not mind losing; they only mind losing slowly.",
    "The birds above the arena sound suspiciously like they are betting on the race. The runners ignore them and keep their eyes on the text.",
    "The finish stripe sits so far away that it feels like a rumor. Then the first few words land cleanly, and the rumor starts to look real.",
    "A long-necked dinosaur provides shade for the whole lane, which feels generous until the sun moves and everyone must speed up again.",
    "The starter claps once, and that is the only warning anyone gets. After that, the keyboard and the racetrack begin telling the same story.",
    "A tiny fossil falls out of the announcer's pocket and rolls across the floor. The crowd gasps, then cheers as if that was always part of the plan.",
    "The racers keep their shoulders relaxed and their fingers ready. This is the kind of calm that can outrun almost anything.",
    "A very serious dinosaur chef brought snacks to the track, because no one wins a race on an empty stomach or a distracted mind.",
    "The mountain path narrows, the cliffs rise, and the typing gets wonderfully focused. Even the wind seems to press the right keys at last.",
    "The parade balloon drifts across the sky and briefly blocks the finish banner. Nobody panics, because the race is about rhythm, not weather.",
    "A runner with shiny shoes performs exactly one dramatic flourish, then remembers there is still a lot of sentence left to type.",
    "The lava field glows behind a fence of polished stone. The racers stay cool, take the next word, and leave the panic to the scenery.",
    "A field guide says the safest way through the jungle is simple: read carefully, breathe once, and do not type the bird names too quickly.",
    "The dinosaur band starts playing an offbeat march that somehow helps everyone concentrate. The keyboard clicks fall right into step.",
    "The grandstand holds its breath as the finish nears. That is usually the moment when the best typing shows up with the least noise.",
    "A new racer arrives late, waves apologetically, and still manages a clean start. The crowd respects that kind of recovery.",
    "The old bridge shakes when the herd crosses, but the words stay steady. Good typing can do the same when the sentence gets long.",
    "The moon rises over the track, turning every lane silver. The racers look almost legendary until they miss a comma and become human again.",
    "A fern brushes the lane marker, a breeze flips the scoreboard ribbon, and the race continues like a small adventure that learned how to run.",
    "The final word lands softly, like a pebble into still water. Then the whole track seems to remember why it was built in the first place.",
  ],
  colors: { navy: "#0d3b66", lemon: "#faf0ca", gold: "#f4d35e", sand: "#ee964b", tomato: "#f95738" },
  adaptiveRatios: [0.95, 0.99, 1.02, 1.05],
  fixedRatios: { easy: 0.75, normal: 1, hard: 1.15 },
  calibrationTexts: [
    `A lantern glows on the porch while the rain taps a patient rhythm on the roof. Inside, the keyboard answers with a quieter pattern, and the whole room seems to agree that consistency is more useful than haste. A good typist reads one phrase at a time, corrects mistakes without panic, and keeps the motion smooth enough to remember. The road ahead may feel long, but long roads are conquered by ordinary steps that refuse to stop.`,
    `The museum hall is empty except for the echo of footsteps and the sound of careful breathing. A note in the display case asks the visitor to slow down, notice the details, and trust that accuracy builds speed in a way that rushing never can. Every accurate keystroke is a small decision, and every small decision adds up to a result that can be seen clearly when the timer ends.`,
    `At the edge of the harbor, gulls argue with the wind while the tide shifts under the pilings. A traveler with a notebook waits for the right moment to begin, then learns that the best opening move is simply the first clean word. The rest follows from attention, not from force. When the sentence grows longer, the steady mind grows stronger too.`,
    `The old library smells like paper, cedar, and a little dust that has earned its place. Shelves rise to the ceiling like patient cliffs, and the reader standing between them understands that practice is its own kind of archive. Each mistake leaves a record, each correction leaves a lesson, and the next line becomes easier because the last one was met with calm hands.`,
    `A train slips through the countryside just after dawn, bright windows cutting across fields still silver with dew. The conductor keeps the pace even, the whistle soft, and the route steady enough that no one needs to worry about the miles. Typing works much the same way when the mind keeps time and the fingers trust the rhythm already chosen.`,
    `The garden path bends around roses, stone benches, and a fountain that never seems to hurry. A beginner might think speed is the whole game, but the garden knows better: the best growth happens when attention remains gentle and repeatable. The sentence in front of you is not a wall; it is a path with a few extra twists, and those twists can be handled one careful step at a time.`,
    `A workshop bench holds half-finished inventions, sharpened pencils, and one very determined clock. Nothing on the table is impressive by itself, but together the tools suggest a simple truth: useful work is built piece by piece. A typist who keeps calm through each correction will often outrun someone who tries to sprint through the mistakes.`,
    `The river widens before it reaches the bridge, reflecting a sky full of late afternoon color. People cross in both directions, each carrying a different story, but the bridge never asks them to hurry. It only asks them to keep moving. Practice is the same kind of crossing, and every line typed cleanly is another plank set in place.`,
    `A mountain trail climbs through pines so tall they seem to hold the clouds at arm's length. The air grows thinner, the steps grow slower, and yet the view at the top still belongs to the person who kept going. A long calibration passage can feel like that climb, which is why a patient typist reads ahead and trusts the next breath.`,
    `The market opens before sunrise, when the stalls are quiet and the sellers are still arranging baskets, jars, and folded cloth. By noon the place will be loud enough to feel like another language, but the first hour is all about order. Typing has a similar hour at the start of every race, when the body settles and the sentence begins to ask for focus.`,
    `A lighthouse stands where land ends and the weather begins. Each flash of light feels small compared with the dark, yet the small flashes are exactly what the sailors need. In the same way, a single correct letter can guide the entire passage. That is why steady practice matters: it turns a little light into a reliable path.`,
    `The classroom door opens onto a hush of chalk dust, wooden desks, and books waiting to be opened. A student sits down, hears the clock, and realizes that learning is often just the repeatable act of paying attention. On a keyboard, that attention becomes movement, and movement becomes speed only after accuracy has already done its quiet work.`,
    `An orchard in autumn is full of color, but the important part is the pattern hidden inside the branches. Each tree has a rhythm, each fruit hangs a little differently, and yet the harvest only succeeds when someone notices what is ready now. Typing rewards the same kind of observation. Read the line, place the letter, and let the work unfold in order.`,
    `The harbor fog lifts slowly enough that the boats appear one at a time, as if the morning is introducing them carefully. That is a useful lesson for fast typing: complexity is easier to manage when it arrives in pieces. A long passage can still feel friendly if the reader keeps looking at the next clear piece instead of the whole foggy harbor.`,
    `A candle burns beside an open notebook, and the flame steadies whenever the window closes against the wind. The room becomes a small workshop for thought. If a mistake appears, the page does not mind; it only asks for another attempt. That is the heart of a good calibration run and the reason practice can become progress.`,
    `On the docks, ropes creak, gulls shout, and a crew of tired sailors loads the last crates before the tide turns. Nobody gets the timing perfect on the first try, but everyone learns the rhythm by moving with the water rather than against it. Typing follows the same rule when the hands remember to listen more than they rush.`,
    `The old station clock keeps time for travelers who arrive too early and for travelers who arrive too late. Both kinds of people need the same thing: a clear next step. A typing test rewards that same clarity. Read the next character, press the next key, and let the result come from a series of ordinary choices done well.`,
    `A campfire gathers its light from a pile of small sticks, not from one heroic log. The flames brighten because each small piece is placed with care. That is exactly how accuracy builds speed over sixty seconds. The hands do not need to be dramatic; they only need to be consistent enough to keep the fire alive.`,
    `The river delta spreads into many channels, but each branch still leads toward the sea. A person who types quickly without losing control is doing the same thing: splitting attention into small, manageable streams that all return to one goal. The race feels faster when the mind understands where the water is going.`,
    `At the end of a long road, the inn lights its windows before the travelers can see the sign. That small welcome is enough to keep everyone moving. A good calibration passage should work the same way: it should be long enough to reveal a true pace, but clear enough that the reader keeps confidence all the way through.`,
  ],
  calibrationText: `Every steady practice session turns small movements into useful habits. Keep your shoulders relaxed and let your fingers travel lightly across the keys. Accuracy creates a rhythm that speed can follow. When a difficult word appears, stay calm, correct it, and continue. The goal is not to rush every letter but to build a pace you can trust. Morning light stretches across the path while runners gather near the starting line. A cool breeze moves through the trees and carries the sound of shoes against the track. Each racer has a different rhythm, yet everyone moves toward the same bright finish. Focus on the next character, then the next word, and allow the sentence to unfold naturally. Strong typing grows from patient repetition, clear attention, and the confidence to recover from mistakes. Keep looking ahead while your hands do the work. The road becomes easier when your eyes remain on the text and your breathing stays even. Practice rewards consistency more than a single burst of speed. Today is a useful starting point, and every future race offers another chance to move a little faster with a little more control.`,
};

export const THEMES = [
  { id: "sunset-sprint", name: "Sunset Sprint", themeColor: "#0d3b66" },
  { id: "stormy-teal", name: "Stormy Teal", themeColor: "#284b63" },
  { id: "coral-slate", name: "Coral Slate", themeColor: "#2d3142" },
  { id: "solar-rally", name: "Solar Rally", themeColor: "#003049" },
  { id: "pumpkin-coast", name: "Pumpkin Coast", themeColor: "#004e98" },
  { id: "forest-trail", name: "Forest Trail", themeColor: "#344e41" },
];

const GENERAL_CHALLENGES = [
  { id: 'general-01', title: 'Morning Warmup', category: 'General', enabled: true, text: 'Morning light runs along the track while every racer settles into a clean rhythm. Keep your hands relaxed, trust the next letter, and let accuracy pull the sentence forward.' },
  { id: 'general-02', title: 'Steady Climb', category: 'General', enabled: true, text: 'A strong pace begins with small decisions repeated well. Each corrected mistake teaches your fingers where to land, and each finished line adds another step up the hill.' },
  { id: 'general-03', title: 'Harbor Wind', category: 'General', enabled: true, text: 'A salt breeze moves across the harbor and rattles the flags above the starting line. The runners lean into the turn, listening for the rhythm hidden inside the noise.' },
  { id: 'general-04', title: 'Quiet Focus', category: 'General', enabled: true, text: 'The best practice often feels ordinary while it is happening. You breathe, read the next word, tap the right keys, and discover afterward that ordinary minutes became real progress.' },
  { id: 'general-05', title: 'Bright Finish', category: 'General', enabled: true, text: 'The finish stripe waits in the distance, clear and still. Your job is not to chase every letter at once, but to meet one character after another with calm attention.' },
  { id: 'general-06', title: 'Desert Shortcut', category: 'General', enabled: true, text: 'Dust lifts behind the racers as they follow a winding desert shortcut. A clever path only helps when each step is steady enough to carry speed without losing control.' },
  { id: 'general-07', title: 'Lantern Trail', category: 'General', enabled: true, text: 'Lanterns glow beside the trail as evening settles over the course. The path looks different in softer light, yet the rule remains simple: read carefully and keep moving.' },
  { id: 'general-08', title: 'Practice Signal', category: 'General', enabled: true, text: 'Every mistake is a signal, not a verdict. Notice it, correct it, and return to the sentence before frustration steals energy that belongs to the race.' },
  { id: 'general-09', title: 'Thunder Run', category: 'General', enabled: true, text: 'Clouds gather over the grandstand while the runners stretch at the line. The first rumble sounds distant, but the track already feels charged with motion.' },
  { id: 'general-10', title: 'Patient Speed', category: 'General', enabled: true, text: 'Speed that ignores accuracy collapses quickly. Patient speed lasts longer because it knows where the letters are and refuses to waste motion on panic.' },
  { id: 'general-11', title: 'Map Room', category: 'General', enabled: true, text: 'A dusty map lies open on the table, marked with routes no one has tried in years. The winning path begins where curiosity meets careful planning.' },
  { id: 'general-12', title: 'Green Valley', category: 'General', enabled: true, text: 'The valley opens wide below the ridge, full of bright grass and wandering streams. Even a difficult race feels lighter when the road gives you room to breathe.' },
  { id: 'general-13', title: 'Clockwork Steps', category: 'General', enabled: true, text: 'The old clock above the station ticks in a stubborn rhythm. Match that steadiness with your hands, and the passage will move forward like gears finding their teeth.' },
  { id: 'general-14', title: 'Hidden Gate', category: 'General', enabled: true, text: 'The hidden gate is not opened by force, but by noticing the small stone that everyone else missed. Careful attention turns a wall into a doorway.' },
  { id: 'general-15', title: 'Rainy Practice', category: 'General', enabled: true, text: 'Rain taps against the window while the keyboard clicks inside. The weather may change the mood, but steady practice keeps its own bright shelter.' },
  { id: 'general-16', title: 'Long Bridge', category: 'General', enabled: true, text: 'The bridge stretches farther than it first appeared, but every plank supports the next step. Long passages work the same way when you stop measuring the whole distance.' },
  { id: 'general-17', title: 'Campfire Plan', category: 'General', enabled: true, text: 'Around the campfire, every racer explains a different plan for tomorrow. The best one is simple enough to remember when the starting horn sounds.' },
  { id: 'general-18', title: 'River Bend', category: 'General', enabled: true, text: 'The river bends sharply near the old mill, pulling the current into a silver curve. Good typing follows the bend without fighting the shape of the sentence.' },
  { id: 'general-19', title: 'Second Wind', category: 'General', enabled: true, text: 'The second wind arrives quietly, often after the part where stopping sounded reasonable. Keep typing through that moment and let the rhythm find you again.' },
  { id: 'general-20', title: 'Workshop Light', category: 'General', enabled: true, text: 'A warm workshop light falls across scattered tools and half-finished ideas. Skill grows here, where patient hands return to the work until it finally fits.' },
  { id: 'general-21', title: 'Open Field', category: 'General', enabled: true, text: 'The course crosses an open field where there is nothing to hide behind. That can feel intimidating, but clear space also means a clean view of the finish.' },
  { id: 'general-22', title: 'Small Compass', category: 'General', enabled: true, text: 'A small compass is useful because it answers one question again and again. Practice works the same way when you let accuracy point you back toward progress.' },
  { id: 'general-23', title: 'Midnight Train', category: 'General', enabled: true, text: 'The midnight train carries tired travelers through towns of yellow windows and quiet streets. Its steady wheels remind you that motion can be calm and still arrive on time.' },
  { id: 'general-24', title: 'Garden Steps', category: 'General', enabled: true, text: 'Stone steps climb through a garden crowded with leaves and blue flowers. Each step is plain by itself, but together they lift you somewhere worth seeing.' },
  { id: 'general-25', title: 'Rooftop Race', category: 'General', enabled: true, text: 'From the rooftops, the city looks like a puzzle of lights and lanes. The fastest runner is the one who can see the next safe landing.' },
  { id: 'general-26', title: 'Fresh Page', category: 'General', enabled: true, text: 'A fresh page can feel empty or inviting depending on your courage. Begin with one clean sentence, and the blank space starts working with you.' },
  { id: 'general-27', title: 'Signal Fire', category: 'General', enabled: true, text: 'A signal fire burns on the ridge, telling distant friends that the path is safe. Clear writing does the same thing for readers who arrive later.' },
  { id: 'general-28', title: 'Old Library', category: 'General', enabled: true, text: 'The old library smells like dust, raincoats, and stories that refused to disappear. Every shelf seems to whisper that patience can outlast noise.' },
  { id: 'general-29', title: 'Canyon Echo', category: 'General', enabled: true, text: 'Your footsteps echo between canyon walls, returning slightly changed each time. Practice is an echo too, repeating the lesson until your hands finally believe it.' },
  { id: 'general-30', title: 'Fast Learner', category: 'General', enabled: true, text: 'A fast learner is not someone who never misses. A fast learner notices the miss quickly, changes course, and keeps enough confidence to try again.' },
  { id: 'general-31', title: 'Blue Horizon', category: 'General', enabled: true, text: 'The horizon turns blue where the road disappears into morning haze. You cannot see the whole route yet, but the next few steps are visible enough.' },
  { id: 'general-32', title: 'Puzzle Box', category: 'General', enabled: true, text: 'The puzzle box opens only when every piece moves in the right order. Typing a sentence asks for the same respectful attention to sequence.' },
  { id: 'general-33', title: 'Festival Race', category: 'General', enabled: true, text: 'Drums roll near the festival gate as banners snap in the wind. The crowd is loud, but the racer hears only breath, footsteps, and the next letter.' },
  { id: 'general-34', title: 'Careful Sparks', category: 'General', enabled: true, text: 'A bright idea can arrive like a spark, but useful work keeps it alive. Protect the spark with structure, patience, and enough focus to finish.' },
  { id: 'general-35', title: 'Mountain Light', category: 'General', enabled: true, text: 'Sunlight reaches the mountain peaks before the valley floor. Progress sometimes works that way, showing a little brightness before the whole path becomes clear.' },
  { id: 'general-36', title: 'Tidy Desk', category: 'General', enabled: true, text: 'A tidy desk will not type the paragraph for you, but it can remove one more distraction. Clear space gives attention a better place to stand.' },
  { id: 'general-37', title: 'Deep Breath', category: 'General', enabled: true, text: 'Before the race begins, take one deep breath and let your shoulders drop. A relaxed start gives your hands permission to move with less noise.' },
  { id: 'general-38', title: 'Treasure Note', category: 'General', enabled: true, text: 'The treasure note was written in plain language because the finder would already have enough trouble. Good instructions respect the person who has to use them.' },
  { id: 'general-39', title: 'Hilltop Signal', category: 'General', enabled: true, text: 'From the hilltop, you can see every curve of the course below. Planning is useful, but the race still happens one step and one letter at a time.' },
  { id: 'general-40', title: 'Brave Revision', category: 'General', enabled: true, text: 'Revision is bravery in practical clothes. It admits that the first attempt was not perfect and still believes the next version can be better.' },
  { id: 'general-41', title: 'Silver Keys', category: 'General', enabled: true, text: 'The silver keys hang beside the door, each one shaped for a different lock. Knowledge works best when you choose the right tool for the right moment.' },
  { id: 'general-42', title: 'Sunny Detour', category: 'General', enabled: true, text: 'A sunny detour leads the runners past orange trees and quiet fences. The longer path may still be useful if it keeps your pace steady.' },
  { id: 'general-43', title: 'Storm Shelter', category: 'General', enabled: true, text: 'The storm shelter is built before the sky turns dark. Good habits are built the same way, ready to help when pressure arrives.' },
  { id: 'general-44', title: 'Clear Water', category: 'General', enabled: true, text: 'Clear water reveals the stones beneath the surface. Clear thinking does something similar, showing which problem is real and which one only looked frightening.' },
  { id: 'general-45', title: 'Letter Bridge', category: 'General', enabled: true, text: 'Letters become words, words become sentences, and sentences become a bridge between two minds. Cross it carefully, and the other side will understand you.' },
  { id: 'general-46', title: 'Trail Markers', category: 'General', enabled: true, text: 'Trail markers are small, but they keep travelers from wandering into trouble. Punctuation plays a similar role when a sentence needs direction.' },
  { id: 'general-47', title: 'Golden Hour', category: 'General', enabled: true, text: 'Golden hour turns the track warm and forgiving, though the race is still real. Use the friendly light, but do not forget to watch the lane.' },
  { id: 'general-48', title: 'Corner Turn', category: 'General', enabled: true, text: 'The corner turn is where careless runners drift wide. Slow your thoughts for one moment, aim cleanly, and carry better speed out of the bend.' },
  { id: 'general-49', title: 'Last Lantern', category: 'General', enabled: true, text: 'The last lantern beside the path is enough to show the gate. You do not need every answer before taking the next useful step.' },
  { id: 'general-50', title: 'Finish Journal', category: 'General', enabled: true, text: 'After the finish, write down what helped and what got in the way. A short note today can become a better race tomorrow.' }
];

const MOVIE_QUOTES = [
  ["May the Force be with you.", "Star Wars"],
  ["Here's looking at you, kid.", "Casablanca"],
  ["I'll be back.", "The Terminator"],
  ["You can't handle the truth!", "A Few Good Men"],
  ["There's no place like home.", "The Wizard of Oz"],
  ["Nobody puts Baby in a corner.", "Dirty Dancing"],
  ["I'm king of the world!", "Titanic"],
  ["Houston, we have a problem.", "Apollo 13"],
  ["Why so serious?", "The Dark Knight"],
  ["Hasta la vista, baby.", "Terminator 2: Judgment Day"],
  ["To infinity and beyond!", "Toy Story"],
  ["You talking to me?", "Taxi Driver"],
  ["E.T. phone home.", "E.T. the Extra-Terrestrial"],
  ["I feel the need for speed.", "Top Gun"],
  ["Keep the change, ya filthy animal.", "Home Alone"],
  ["Carpe diem. Seize the day.", "Dead Poets Society"],
  ["I'm gonna make him an offer he can't refuse.", "The Godfather"],
  ["As if!", "Clueless"],
  ["Roads? Where we're going, we don't need roads.", "Back to the Future"],
  ["You shall not pass!", "The Fellowship of the Ring"],
  ["My precious.", "The Two Towers"],
  ["Snakes. Why did it have to be snakes?", "Raiders of the Lost Ark"],
  ["I am serious. And don't call me Shirley.", "Airplane!"],
  ["Nobody expects the Spanish Inquisition!", "Monty Python and the Holy Grail"],
  ["Wax on, wax off.", "The Karate Kid"],
  ["Gentlemen, you can't fight in here!", "Dr. Strangelove"],
  ["There's a snake in my boot!", "Toy Story"],
  ["The first rule of Fight Club is: you do not talk about Fight Club.", "Fight Club"],
  ["Great Scott!", "Back to the Future"],
  ["I volunteer as tribute!", "The Hunger Games"],
  ["Say hello to my little friend!", "Scarface"],
  ["You're gonna need a bigger boat.", "Jaws"],
  ["Here's Johnny!", "The Shining"],
  ["Shaken, not stirred.", "Goldfinger"],
  ["Why don't you make like a tree and get out of here?", "Back to the Future"],
  ["We are not in Kansas anymore.", "The Wizard of Oz"],
  ["I'm just a girl, standing in front of a boy, asking him to love her.", "Notting Hill"],
  ["Frankly, my dear, I don't give a damn.", "Gone with the Wind"],
  ["Fasten your seatbelts. It's going to be a bumpy night.", "All About Eve"],
  ["You had me at hello.", "Jerry Maguire"],
  ["Show me the money!", "Jerry Maguire"],
  ["Life finds a way.", "Jurassic Park"],
  ["The stuff that dreams are made of.", "The Maltese Falcon"],
  ["I'm walking here!", "Midnight Cowboy"],
  ["Nobody's perfect.", "Some Like It Hot"],
  ["Inconceivable!", "The Princess Bride"],
  ["Hello there.", "Star Wars"],
  ["I'm as mad as hell, and I'm not going to take this anymore!", "Network"],
  ["I'll have what she's having.", "When Harry Met Sally"],
  ["Elementary, my dear Watson.", "The Adventures of Sherlock Holmes"],
];

const MOVIE_QUOTE_CHALLENGES = MOVIE_QUOTES.map(([text, source], index) => ({
  id: `movie-${String(index + 1).padStart(2, "0")}`,
  title: `Movie Quote ${String(index + 1).padStart(2, "0")}`,
  category: "Movie Quotes",
  enabled: true,
  source,
  text,
}));

const BOOK_SOURCES = [
  "Inspired by Harry Potter and the Sorcerer's Stone", "Inspired by Treasure Island", "Inspired by Alice's Adventures in Wonderland", "Inspired by The Secret Garden", "Inspired by The Wonderful Wizard of Oz",
  "Inspired by Little Women", "Inspired by Anne of Green Gables", "Inspired by The Hobbit", "Inspired by The Chronicles of Narnia", "Inspired by A Wrinkle in Time",
  "Inspired by Sherlock Holmes", "Inspired by The Jungle Book", "Inspired by Peter Pan", "Inspired by The Wind in the Willows", "Inspired by Black Beauty",
  "Inspired by Frankenstein", "Inspired by Dracula", "Inspired by The War of the Worlds", "Inspired by Twenty Thousand Leagues Under the Seas", "Inspired by Journey to the Center of the Earth",
  "Inspired by The Call of the Wild", "Inspired by White Fang", "Inspired by Around the World in Eighty Days", "Inspired by The Three Musketeers", "Inspired by Robin Hood",
  "Inspired by The Swiss Family Robinson", "Inspired by The Count of Monte Cristo", "Inspired by Jane Eyre", "Inspired by Pride and Prejudice", "Inspired by Great Expectations",
  "Inspired by Oliver Twist", "Inspired by Moby-Dick", "Inspired by The Odyssey", "Inspired by The Iliad", "Inspired by Don Quixote",
  "Inspired by The Little Prince", "Inspired by Charlotte's Web", "Inspired by Matilda", "Inspired by Charlie and the Chocolate Factory", "Inspired by The Giver",
  "Inspired by The Hunger Games", "Inspired by Percy Jackson", "Inspired by The Lightning Thief", "Inspired by The Book Thief", "Inspired by The Maze Runner",
  "Inspired by The Princess Bride", "Inspired by Watership Down", "Inspired by The Phantom Tollbooth", "Inspired by The Outsiders", "Inspired by A Christmas Carol"
];

const BOOK_LINES = [
  "A young reader opens a forbidden door and discovers that courage can begin with curiosity, even when the hallway beyond is darker than expected.",
  "The map is torn, the weather is turning, and the only sensible plan is to trust the crew member who still remembers how to read the stars.",
  "In a garden that everyone forgot, one stubborn green shoot proves that hidden places can come alive again when someone cares enough to return.",
  "The smallest traveler in the room asks the sharpest question, and suddenly every grown-up has to admit that the impossible rule was only tradition.",
  "A letter arrives at breakfast and changes the shape of the day, reminding the hero that ordinary houses can hide extraordinary invitations.",
  "The old road bends through fog and firelight, where friends learn that loyalty is easier to promise at home than to practice on the journey.",
  "A clever clue waits in plain sight on the dusty shelf, ignored by everyone except the person willing to read the boring label twice.",
  "The sea keeps its secrets under a bright moon, and the captain knows that every treasure has a cost written somewhere in smaller print.",
  "A lonely child finds a key, a question, and a reason to believe that locked rooms sometimes protect wounded hearts rather than treasure.",
  "The final page is not the end of the adventure; it is the place where the reader carries the lesson back into real life."
];

const BOOK_CHALLENGES = BOOK_SOURCES.map((source, index) => ({
  id: `book-${String(index + 1).padStart(2, "0")}`,
  title: `Book Challenge ${String(index + 1).padStart(2, "0")}`,
  category: "Books",
  source,
  enabled: true,
  text: BOOK_LINES[index % BOOK_LINES.length],
}));

const LORD_OF_THE_RINGS_SOURCES = [
  "Inspired by The Fellowship of the Ring", "Inspired by The Two Towers", "Inspired by The Return of the King", "Inspired by The Hobbit", "Inspired by Middle-earth"
];

const LORD_OF_THE_RINGS_LINES = [
  "A small traveler stands at the edge of a road that has carried kings, wanderers, and warnings, then chooses the next step anyway.",
  "The mountain looks impossibly far, but faithful company makes the distance feel less like doom and more like a promise carried together.",
  "In the deep places of the world, courage is not loud; it is the quiet decision to keep the light uncovered for one more turn.",
  "A ranger listens to the wind across the grasslands and understands that hope can move unseen before anyone is ready to name it.",
  "The old tales return when ordinary hands accept an extraordinary burden, proving that history often depends on those who never asked for fame.",
  "Across the river, towers and shadows argue with the morning, but the company presses on because some roads can only be honored by walking them.",
  "A door in the stone remembers a kinder age, waiting for the right word, the right friend, and the patience to look again.",
  "The forest feels ancient enough to judge every footstep, yet even under tangled branches a clear song can keep fear from taking root.",
  "When the horn sounds over the field, every heart must decide whether it belongs to panic or to the hard work of standing firm.",
  "The ring is heavy because temptation always weighs more than metal, especially when it whispers that power can make sacrifice unnecessary."
];

const LORD_OF_THE_RINGS_CHALLENGES = Array.from({ length: 50 }, (_, index) => ({
  id: `lotr-${String(index + 1).padStart(2, "0")}`,
  title: `Lord of the Rings Practice ${String(index + 1).padStart(2, "0")}`,
  category: "Lord of the Rings Quotes",
  source: LORD_OF_THE_RINGS_SOURCES[index % LORD_OF_THE_RINGS_SOURCES.length],
  enabled: true,
  text: LORD_OF_THE_RINGS_LINES[index % LORD_OF_THE_RINGS_LINES.length],
}));

const TYPING_BASICS_LESSONS = [
  { title: "Lesson 01 - Find F and J", text: "fff jjj fff jjj fjf jfj fff jjj fj fj fj jf jf jf" },
  { title: "Lesson 02 - Left Home Keys", text: "aaa sss ddd fff asdf fdsa asdf fdsa sad dad fad add" },
  { title: "Lesson 03 - Right Home Keys", text: "jjj kkk lll ;;; jkl; ;lkj jkl; ;lkj all fall hall" },
  { title: "Lesson 04 - Home Row Outward", text: "f j d k s l a ; f j d k s l a ; fj dk sl a;" },
  { title: "Lesson 05 - Home Row Inward", text: "a ; s l d k f j a; sl dk fj fj dk sl a;" },
  { title: "Lesson 06 - Reach G and H", text: "fff ggg fff gfg jjj hhh jjj hjh fg hj gh gh fg hj" },
  { title: "Lesson 07 - Alternate Hands", text: "fj dk sl ah fj dk sl ah fad had dash flask ask hall" },
  { title: "Lesson 08 - Home Row Words", text: "ask dad fall glad hall salad flask dash half shall" },
  { title: "Lesson 09 - Home Row Rhythm", text: "a sad lad had a flask; a glad lass had a salad;" },
  { title: "Lesson 10 - Home Row Review", text: "asdf jkl; glad falls; a dash; ask a lad; half a salad;" },
  { title: "Lesson 11 - Left Top Keys", text: "qqq www eee rrr qwer rewq qwe wer ert tree were" },
  { title: "Lesson 12 - Right Top Keys", text: "uuu iii ooo ppp uiop poiu you oil pool loop upon" },
  { title: "Lesson 13 - Reach T and Y", text: "fff ttt fff ftf jjj yyy jjj jyj try yet type toy" },
  { title: "Lesson 14 - Top Row Sequence", text: "qwerty uiop qwerty uiop poiuy trewq type your power" },
  { title: "Lesson 15 - Left Top Words", text: "read dear fear free rate water street after great" },
  { title: "Lesson 16 - Right Top Words", text: "you pull oil loop joy poll lily hill until point" },
  { title: "Lesson 17 - Common Top Words", text: "the there they were your four quiet people write" },
  { title: "Lesson 18 - Top and Home", text: "we type with steady hands and read each word first" },
  { title: "Lesson 19 - Top Row Accuracy", text: "quiet writers prefer a slow start to a hurried error" },
  { title: "Lesson 20 - Top Row Review", text: "type every word with light hands; pause and try again" },
  { title: "Lesson 21 - Left Bottom Keys", text: "zzz xxx ccc vvv zxcv vcxz zip wax cave vivid exact" },
  { title: "Lesson 22 - Right Bottom Keys", text: "bbb nnn mmm bnm mnb bin nimble number banana menu" },
  { title: "Lesson 23 - Bottom Row Sequence", text: "zxcvbnm zxcvbnm mnbvcxz zoom cabin mix brave calm" },
  { title: "Lesson 24 - Reach C V and B", text: "dcd fvf fbf cab cave civic vivid brave basic cub" },
  { title: "Lesson 25 - Reach N and M", text: "jnj kmk man name moon nine minimum animal lemon" },
  { title: "Lesson 26 - Left Bottom Words", text: "save face cave exact value civic brave scarf vast" },
  { title: "Lesson 27 - Right Bottom Words", text: "main moon name number lemon banana minimum combine" },
  { title: "Lesson 28 - Three Row Words", text: "quick brown fox jumps over the lazy dog with care" },
  { title: "Lesson 29 - Alphabet Patterns", text: "abc def ghi jkl mno pqr stu vwx yz abcdefghijklmnop" },
  { title: "Lesson 30 - All Letter Review", text: "bright zebras quickly move across the calm valley" },
  { title: "Lesson 31 - Space Control", text: "one two three four five one two three four five" },
  { title: "Lesson 32 - Short Common Words", text: "a an as at be by do go he if in is it me my no of on" },
  { title: "Lesson 33 - Common Word Pairs", text: "in the on the to the of the we can you can I can" },
  { title: "Lesson 34 - First Short Sentence", text: "the red fox can run fast and the blue bird can fly" },
  { title: "Lesson 35 - Sentence Rhythm", text: "keep a calm pace and let each clean word lead onward" },
  { title: "Lesson 36 - Left Shift Capitals", text: "Alice David Frank Grace Alice David Frank Grace" },
  { title: "Lesson 37 - Right Shift Capitals", text: "Peter Quinn Robert Taylor Peter Quinn Robert Taylor" },
  { title: "Lesson 38 - Names and Places", text: "Mia and Noah plan a calm trip from Boston to Denver" },
  { title: "Lesson 39 - Period Practice", text: "Type one clean line. Pause for a breath. Begin again." },
  { title: "Lesson 40 - Comma Practice", text: "Pack a map, a coat, a snack, and a small blue cup." },
  { title: "Lesson 41 - Apostrophe Practice", text: "I can type what's next, and I'll correct what isn't right." },
  { title: "Lesson 42 - Semicolon Practice", text: "Keep the left hand calm; let the right hand reach; continue." },
  { title: "Lesson 43 - Question Practice", text: "Can you find the next key? Will you type it with care?" },
  { title: "Lesson 44 - Exclamation Practice", text: "Great work! Keep your hands light! Finish with control!" },
  { title: "Lesson 45 - Quotation Practice", text: "\"Ready,\" said Mia. \"I can type this line with care.\"" },
  { title: "Lesson 46 - Numbers One to Five", text: "1 2 3 4 5 12345 54321 11 22 33 44 55" },
  { title: "Lesson 47 - Numbers Six to Zero", text: "6 7 8 9 0 67890 09876 66 77 88 99 00" },
  { title: "Lesson 48 - Numbers and Words", text: "I have 2 hands, 10 fingers, 5 goals, and 1 steady pace." },
  { title: "Lesson 49 - Mixed Punctuation", text: "Ready, set, type! Is it clear? Yes; keep going." },
  { title: "Lesson 50 - Beginner Graduation", text: "Calm hands, clear eyes, and steady practice help every new typist grow faster." },
];

const TYPING_BASICS_CHALLENGES = TYPING_BASICS_LESSONS.map((lesson, index) => ({
  id: `typing-basics-${String(index + 1).padStart(2, "0")}`,
  title: lesson.title,
  category: "Typing Basics",
  source: "Dino Type Racer Beginner Course",
  enabled: true,
  text: lesson.text,
}));
const INTERMEDIATE_TYPING_LESSONS = Array.from({ length: 50 }, (_, index) => {
  const lesson = index + 1;
  const patterns = [
    "Clean speed comes from reading ahead, striking the next key once, and letting each finished word carry you smoothly into the next.",
    "Practice mixed reach keys with steady hands: travel from home row to top row, return to center, then move to bottom row without rushing.",
    "Every paragraph asks for rhythm, accuracy, and recovery; correct the slip quickly, breathe once, and keep the sentence moving forward.",
    "Use capital letters, commas, and periods with purpose. The goal is not raw speed, but a pace that survives real writing.",
    "Numbers appear in ordinary text: 3 laps, 12 minutes, 48 steps, and 100 small choices can still become one confident race.",
    "The left hand leads, the right hand answers, and both hands learn to share the work across longer words like careful, garden, and forward.",
    "When the passage grows longer, keep your eyes moving ahead of your fingers so each word feels expected before it arrives.",
    "A good intermediate run feels alert but not frantic; it leaves enough attention for punctuation, spacing, and a clean finish.",
    "Shift between short words and longer words: can, careful, type, practice, road, reliable, focus, and championship all deserve accuracy.",
    "Build the habit of finishing strong, because the final sentence matters as much as the first line after the countdown begins.",
  ];
  return {
    title: `Intermediate ${String(lesson).padStart(2, "0")} - ${["Flow Control", "Mixed Rows", "Recovery", "Real Sentences", "Numbers", "Hand Balance", "Reading Ahead", "Calm Speed", "Word Length", "Strong Finish"][index % 10]}`,
    text: `${patterns[index % patterns.length]} Round ${lesson} adds a little more control without asking your hands to panic.`,
  };
});

const INTERMEDIATE_TYPING_CHALLENGES = INTERMEDIATE_TYPING_LESSONS.map((lesson, index) => ({
  id: `typing-intermediate-${String(index + 1).padStart(2, "0")}`,
  title: lesson.title,
  category: "Typing Intermediate",
  source: "Dino Type Racer Intermediate Course",
  enabled: true,
  text: lesson.text,
}));

const ADVANCED_TYPING_LESSONS = Array.from({ length: 50 }, (_, index) => {
  const lesson = index + 1;
  const patterns = [
    "Accuracy under pressure is a trained skill: read the phrase, commit to the sequence, and refuse to trade clean movement for noise.",
    "Advanced passages mix commas, semicolons, quotes, numbers, and abrupt word lengths; your job is to keep the rhythm organized.",
    "The racer who wins difficult text does not attack every character; they see patterns, reduce wasted motion, and recover before doubt spreads.",
    "Type this like a proofreader with fast shoes: every mark counts, every space matters, and every correction teaches the next attempt.",
    "Complex work rewards a calm system. Hold the line through 7 sharp turns, 24 quick reaches, and one final burst of focus.",
    "Use both Shift keys wisely when Names, Places, and Ideas arrive together; balanced hands keep capitalization from stealing momentum.",
    "Longer sentences demand patience, because the mind wants to jump ahead while the fingers still owe the current word their full attention.",
    "When punctuation clusters appear, slow by a breath instead of a mile; a precise comma is faster than a repaired mistake.",
    "Advanced typing is not a storm of keystrokes. It is controlled speed, clean spacing, and the courage to stay exact while moving fast.",
    "Finish the hard line with the same care that started it: strong racers do not let the last five words become a messy victory lap.",
  ];
  return {
    title: `Advanced ${String(lesson).padStart(2, "0")} - ${["Pressure", "Symbols", "Pattern Sight", "Proof Speed", "Turns", "Shift Control", "Endurance", "Punctuation", "Controlled Speed", "Final Push"][index % 10]}`,
    text: `${patterns[index % patterns.length]} Challenge ${lesson} is built for sharper pacing, cleaner punctuation, and steadier recovery.`,
  };
});

const ADVANCED_TYPING_CHALLENGES = ADVANCED_TYPING_LESSONS.map((lesson, index) => ({
  id: `typing-advanced-${String(index + 1).padStart(2, "0")}`,
  title: lesson.title,
  category: "Typing Advanced",
  source: "Dino Type Racer Advanced Course",
  enabled: true,
  text: lesson.text,
}));
export const STARTER_PASSAGES = [
  ...TYPING_BASICS_CHALLENGES,
  ...INTERMEDIATE_TYPING_CHALLENGES,
  ...ADVANCED_TYPING_CHALLENGES,
  ...GENERAL_CHALLENGES,
  ...MOVIE_QUOTE_CHALLENGES,
  ...BOOK_CHALLENGES,
  ...LORD_OF_THE_RINGS_CHALLENGES,
];
